teleop_twist_joy_node:
  ros__parameters:
    axis_linear:  # Left thumb stick vertical
      x: 1
    scale_linear:
      x: 1.5
    scale_linear_turbo:
      x: 3.

    axis_angular:  # Right thumb stick horizontal
      yaw: 3
    scale_angular:
      yaw: 1.

    enable_button: 2  # Left trigger button
    enable_turbo_button: 5  # Right trigger button
